// questions.js
export const questions = [
	{
		type: 'input',
		name: 'projectName',
		message: 'What is your project named?',
		default: 'my-app',
	},
	{
		type: 'list',
		name: 'useTypeScript',
		message: 'Would you like to use TypeScript?',
		choices: ['Yes', 'No'],
		default: 'Yes',
	},
	{
		type: 'list',
		name: 'useESLint',
		message: 'Would you like to use ESLint?',
		choices: ['Yes', 'No'],
		default: 'Yes',
	},
	{
		type: 'list',
		name: 'usePrettier',
		message: 'Would you like to use Prettier for code formatting?',
		choices: ['Yes', 'No'],
		default: 'Yes',
	},
	{
		type: 'list',
		name: 'backendFramework',
		message: 'Which backend framework would you like to use?',
		choices: ['Express', 'NestJS', 'Fastify', 'None'],
		default: 'Express',
	},
	{
		type: 'checkbox',
		name: 'useTestingLibraries',
		message: 'Would you like to add popular testing libraries?',
		choices: ['Jest', 'Mocha', 'Chai', 'Supertest'],
	},
	{
		type: 'list',
		name: 'useMorgan',
		message: 'Would you like to install Morgan (HTTP request logger)?',
		choices: ['Yes', 'No'],
		default: 'Yes',
	},
	{
		type: 'list',
		name: 'useCors',
		message: 'Would you like to install CORS (Cross-Origin Resource Sharing)?',
		choices: ['Yes', 'No'],
		default: 'Yes',
	},
	{
		type: 'list',
		name: 'useHelmet',
		message: 'Would you like to install Helmet (HTTP headers security)?',
		choices: ['Yes', 'No'],
		default: 'Yes',
	},
	{
		type: 'list',
		name: 'useHusky',
		message: 'Would you like to use Husky for Git hooks?',
		choices: ['Yes', 'No'],
		default: 'Yes',
	},
	{
		type: 'list',
		name: 'useDocker',
		message: 'Would you like to use Docker?',
		choices: ['Yes', 'No'],
		default: 'Yes',
	},
]
